# Generated by Django 3.1.7 on 2021-04-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=120)),
                ('cpf', models.IntegerField()),
                ('number', models.IntegerField()),
                ('email', models.CharField(max_length=120)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
